"""
Django settings for shunsite project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'k@vly!$$i#93tn!l3=2)$a660mk21x2%uv+zn$=vhnh^&m@_m$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True   ## 當網站正式上線的時候會需要做一些調整，避免結構暴露在外部 視窗。
# DEBUG = False   ## 當網站正式上線的時候會需要做一些調整，避免結構暴露在外部 視窗。
ALLOWED_HOSTS = ['*']





# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gamehub.apps.GamehubConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware', ## 有這一行就可以使用 session 模組
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'shunsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'shunsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'JD',
    #     'USER':'root',
    #     'PASSWORD':'0000',
    #     'HOST':'127.0.0.1',
    #     'PORT':'3306',
    #     'default-character-set':'utf8'
    # }
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'playgame',
        'USER':'pgadmin',
        'PASSWORD':'09354512000',
        'HOST':'114.32.222.77',
        'PORT':'3306',
        'default-character-set':'utf8'
    }
}





# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/


## - -- - -- - --  -- - -- - -- -- - -- - --  -- - -- - -- -- - -- - --  -- - -- - --
## 新增的內容 ，為了運作 gif, 等資源。
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR,"static")
]

STATIC_ROOT = os.path.join(BASE_DIR, "static_all/")

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 's9921316@nctu.edu.tw'
EMAIL_HOST_PASSWORD = '**********'
DEFAULT_FROM_EMAIL = ''

## - -- - -- - --  -- - -- - -- -- - -- - --  -- - -- - -- -- - -- - --  -- - -- - --
#
# LOGGING = {
#
#     'version': 1,
#     'loggers': {
#         'django': {
#             'handlers':['file'],
#             'level':'DEBUG'
#         }
#     },
#     'handlers':{
#         'file':{
#             'level':'DEBUG',
#             'class':'logging.Filehandlers',
#             'filename':'log.log',
#         }
#     },
#     # 'filters': {
#     #
#     # },
#     # 'formatters': {
#     #
#     # }
# }