# Generated by Django 3.1 on 2020-08-17 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamehub', '0002_auto_20200815_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='title',
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='sel02_shun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paly_acc_no', models.IntegerField()),
                ('play_acc_name', models.CharField(max_length=500)),
                ('pre_people', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='tags',
            field=models.ManyToManyField(related_name='articles_related_tags', to='gamehub.Tag'),
        ),
    ]
